services:
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: "telegram_bot"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --auth-host=trust
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5477:5432"
    container_name: telegram_bot_database
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8808:${REST_API_PORT}"
    container_name: telegram_bot_app
    depends_on:
      - database
  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "${RABBIT_MQ_PORT}:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  db-data:
  rabbitmq_data:
