#!/bin/sh

BASE_TELEGRAM_BOT_ENV_KEY="TELEGRAM_BOT_TOKEN"
BASE_TELEGRAM_HANDLE_URL_ENV_KEY="TELEGRAM_HANDLE_URL"

echo "Parsing .env values for setting up telegram webhook"

echo "Getting telegram bot token..."


TELEGRAM_BOT_TOKEN=$(awk -F "=" '$1 == "'$BASE_TELEGRAM_BOT_ENV_KEY'" {print $2}' .env)

echo "Getting telegram handle url for webhook..."

BASE_TELEGRAM_HANDLE_URL=$(awk -F "=" '$1 == "'$BASE_TELEGRAM_HANDLE_URL_ENV_KEY'" {print $2}' .env)

echo "Getting tuna url from args..."

TUNA_URL=$(echo $1)

if $TUNA_URL; then
    echo "Tuna url was not found in bash script arguments.\\Exiting script..."
    exit 1
fi

echo "Creating http request to [https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/setWebhook?url=$TUNA_URL/$BASE_TELEGRAM_HANDLE_URL]"

RESPONSE=$(curl -i https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/setWebhook?url=$TUNA_URL/$BASE_TELEGRAM_HANDLE_URL)

if echo "$RESPONSE" | grep -q '"ok":true'; then
    echo "Telegram bot weebhook was successfully setuped"
else
    echo "An error occures while trying to setup telegram webhook;\\nResponse: $RESPONSE"
fi
