#!/bin/sh

BASE_TELEGRAM_BOT_ENV_KEY="TELEGRAM_BOT_TOKEN"
BASE_TELEGRAM_HANDLE_URL_ENV_KEY="TELEGRAM_HANDLE_URL"

print_dottes() {
    for i in $(seq 1 10)
    do
        echo ".\c"
        sleep 0.05
    done
    echo
}

echo "Parsing .env values for setting up telegram webhook"

echo "Getting telegram bot token..."

print_dottes

TELEGRAM_BOT_TOKEN=$(awk -F "=" '$1 == "'$BASE_TELEGRAM_BOT_ENV_KEY'" {print $2}' .env)

echo "Getting telegram handle url for webhook..."

print_dottes

BASE_TELEGRAM_HANDLE_URL=$(awk -F "=" '$1 == "'$BASE_TELEGRAM_HANDLE_URL_ENV_KEY'" {print $2}' .env)

echo "Getting tuna url from args..."

print_dottes

TUNA_URL=$(echo $1)

if $TUNA_URL; then
    echo "Tuna url was not found in bash script arguments.\\nExecuting script..."
    exit 1
fi

echo "Creating http request to [https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/setWebhook?url=$TUNA_URL/$BASE_TELEGRAM_HANDLE_URL]"

print_dottes

RESPONSE=$(curl -i https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/setWebhook?url=$TUNA_URL/$BASE_TELEGRAM_HANDLE_URL)

if echo "$RESPONSE" | grep -q '"ok":true'; then
    echo "Telegram bot weebhook was successfully setuped"
else
    echo "An error occures while trying to setup telegram webhook;\\nResponse: $RESPONSE"
fi
