name: telegram music bot pipelines

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  run make:
    runs-on: ubuntu-latest
    steps:
    - name: run make
      run: make build